### ISSUE TITLE
Во время загрузки фото произошла ошибка

### ISSUE THREAD

**Issue by AVert** [maxfarseer/redux-course-ru-v2#6]
не грузит фото (((

**Comment by AVert** [comment]
![image](https://user-images.githubusercontent.com/316002/47088919-4d2b2c80-d228-11e8-94e8-00dde19dce1f.png)

**Comment by 1cheese** [comment]
Насколько я понял, проблема в том, что при большом количестве фотографий в профиле приложение делает слишком много запросов к VK API, в то время как существует ограничение (https://vk.com/dev/api_requests):

> Максимальное число обращений к методам секции secure зависит от числа пользователей, установивших приложение. Если приложение установило меньше 10 000 человек, то можно совершать 5 запросов в секунду, до 100 000 — 8 запросов, до 1 000 000 — 20 запросов, больше 1 млн. — 35 запросов в секунду. 
> Если Вы превысите частотное ограничение, сервер вернет ошибку с кодом 6: "Too many requests per second.". 

Я решил это следующим образом - добавил setTimeout() в файл PageActions.js:

```javascript
try {
  photosArr = photosArr.concat(r.response.items)
  if (offset <= r.response.count) {
    offset += 200 
    setTimeout(() => {
      getMorePhotos(offset, count, year, dispatch) 
    }, 200)
  } else {
    let photos = makeYearPhotos(photosArr, year)
    cached = true
    dispatch({
      type: GET_PHOTOS_SUCCESS,
      payload: photos,
    })
  }
}
```
